### PR TITLE
Prevent errors when acf isnt present

### PR DESCRIPTION
**Pull request by wrefgtzweve**

### CODE REVIEW

**Review by sarahsturgeon — CHANGES_REQUESTED** [review]
Addon needs more work than this to make it functional without acf

**Comment by wrefgtzweve** [comment]
Such as? the only issue i could see was a missing effect but those don't create any errors

**Review by sarahsturgeon — APPROVED** [review]
I suppose you're right, I remember doing more with ACF before

**Comment by wrefgtzweve** [comment]
I could add a simply if check that displays a normal gmod explosion if acf isn't present, would likely be nicer

**Comment by sarahsturgeon** [comment]
We could just copy the ACF effects into this addon, might be easier

**Comment by wrefgtzweve** [comment]
That's likely going to be a truckload of code, might be cooler if we made our own quirky effect

**Comment by sarahsturgeon** [comment]
Sure, if you'd like to. I'd just copy the two acf effect files and stub any globals in them

**Pull request merged**
